# Python if to function examples

### 파이썬 복습을 위한 코드 문제

## Python if

### if문을 이용해서 판별하기
* 숫자를 입력했을 때, 그 숫자가 짝수/홀수를 판별해라.

In [10]:
# 숫자를 입력했을 때,
num = input(" ")

if int(num) % 2 == 0:
    print("짝수")
else:
    print("홀수")

if int(num) % 2 == 1:
    print("홀수")
else:
    print("짝수")

 6
짝수
짝수

---

### if문을 이용한 데이터 검사
* 주어진 List가 있을 때, 수도권이 아닌 곳은 어디인가요?
```python
citys = ["서울", "인천", "경기"]
```

In [18]:
# num = [1, 2, 3, 5, 7] # 소수
# inputs = input("10 이하의 소수가 아닌 것은?")

# if int(inputs) in num:
#     print("그 숫자는 소수 입니다.")
# else:
#     print("그 숫자는 소수가 아닙니다.")

city = ["서울", "인천", "경기"]
inputs = input("수도권일까요?")

if inputs in city:
    print("수도권 입니다.")
else:
    print("수도권이 아닙니다.")

수도권일까요?경기
수도권

---

### if문을 이용한 점수 분류
* 입력된 점수를 100점부터 20점 단위로 A, B, C 학점을 부여해주세요.

In [20]:
score = input("score : ")
score = int(score)

if 80 < score <=100:
    print("A")
elif 60 < score <= 80:
    print("B")
elif 40 < score <= 60:
    print("C")

score : 88
A

---

## Python Loop

### for 문을 이용한 List 출력
* 주어진 List를 for문 이용해 출력해보세요.
```
city = ["서울", "인천", "경기", "강원", "제주"]
```

In [21]:
city = ["서울", "인천", "경기", "강원", "제주"]

for c in city:
    print(c)

서울
인천
경기
강원
제주

---

### for문과 range를 이용한 출력 조절
* 1부터 50까지 숫자 중 5의 배수를 출력해보세요.

In [25]:
for num in range(5, 51, 5):
    print(num)

5
10
15
20
25
30
35
40
45
50

---

### for문으로 출력 조절
* 아래 출력을 for 문을 이용해서 구현해보세요.
```python
print(10)
print("-------")
print(20)
print("-------")
print(30)
print("-------")
```

In [33]:
for i in range(10,40,10):
    print(i)
    print("-------")

for i in range(0,30,10):
    print(i + 10)
    print("-------")

10
-------
20
-------
30
-------
10
-------
20
-------
30
-------

---

### 구구단 출력하기
* for문을 이용해서 구구단 2단을 출력해보세요.

In [39]:
for j in range(2, 10):
    for i in range(1, 10): # 1~9
        print(j, "x", i, " = ", j * i)
    print("----")

2 x 1  =  2
2 x 2  =  4
2 x 3  =  6
2 x 4  =  8
2 x 5  =  10
2 x 6  =  12
2 x 7  =  14
2 x 8  =  16
2 x 9  =  18
----
3 x 1  =  3
3 x 2  =  6
3 x 3  =  9
3 x 4  =  12
3 x 5  =  15
3 x 6  =  18
3 x 7  =  21
3 x 8  =  24
3 x 9  =  27
----
4 x 1  =  4
4 x 2  =  8
4 x 3  =  12
4 x 4  =  16
4 x 5  =  20
4 x 6  =  24
4 x 7  =  28
4 x 8  =  32
4 x 9  =  36
----
5 x 1  =  5
5 x 2  =  10
5 x 3  =  15
5 x 4  =  20
5 x 5  =  25
5 x 6  =  30
5 x 7  =  35
5 x 8  =  40
5 x 9  =  45
----
6 x 1  =  6
6 x 2  =  12
6 x 3  =  18
6 x 4  =  24
6 x 5  =  30
6 x 6  =  36
6 x 7  =  42
6 x 8  =  48
6 x 9  =  54
----
7 x 1  =  7
7 x 2  =  14
7 x 3  =  21
7 x 4  =  28
7 x 5  =  35
7 x 6  =  42
7 x 7  =  49
7 x 8  =  56
7 x 9  =  63
----
8 x 1  =  8
8 x 2  =  16
8 x 3  =  24
8 x 4  =  32
8 x 5  =  40
8 x 6  =  48
8 x 7  =  56
8 x 8  =  64
8 x 9  =  72
----
9 x 1  =  9
9 x 2  =  18
9 x 3  =  27
9 x 4  =  36
9 x 5  =  45
9 x 6  =  54
9 x 7  =  63
9 x 8  =  72
9 x 9  =  81
----

---

## Python Function

### Hello world!를 출력하는 함수 만들기
* Hello world!를 출력하는 함수를 구현해서 출력해보세요.

In [41]:
def hi():
    print("Hello world!")

hi() # function call

Hello world!

---

### 함수와 연산
* 두개의 정수 값을 입력 받아 곱셈을 출력하는 함수를 구현해보세요.

In [43]:
# a, b 입력 받아서 a * b의 값을 리턴하는 함수를 구현하면 위의 문제를 해결할 수 있습니다.

def multi(a, b):
    return a * b

num1 = 2
num2 = 4

multi(num1, num2)

8

---

### 함수 구현
* 세 숫자를 입력 받아 가장 작은 값을 출력하는 함수를 구현해보세요.

In [47]:
def select_min_number(a, b, c):
    # add
    return min(a, b, c)

select_min_number(3, 1, 5)

1

---